# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: tarikguney.WindowTaskSwitcher
PackageVersion: 0.1.0
Platform:
  - Windows.Desktop
MinimumOSVersion: 10.0.17763.0
InstallerType: portable
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/tarikguney/windows-task-switcher/releases/download/v0.1.0/WindowTaskSwitcher.exe
    InstallerSha256: E0382FFCAB7FBF24416C39CB7A0AFD605EED7FF902C1375E422F876AAFD40646
ManifestType: installer
ManifestVersion: 1.6.0
